### ISSUE TITLE
Java 8 no longer works

### ISSUE THREAD

**Issue by MarkRx** [xtext/xtext-gradle-plugin#187]
[org.eclipse.platform:org.eclipse.equinox.common:3.15.0](https://search.maven.org/artifact/org.eclipse.platform/org.eclipse.equinox.common/3.15.0/jar) was recently published and it gets pulled in from transitive dependency ranges. As a result attempting to run generateXtext fails on any version of xtend and the gradle plugin with a class version error.

*Expected*
xtend 2.25.0 and xtext-gradle-plugin 2.0.8 supports compiling java 8

*Actual*
Using java 8 fails

```
* Exception is:                                                                                                                                    
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':generateXtext'.                                                           
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:103)                  
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:73)                          
        at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)        
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)                              
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)    
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)                                  
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)             
        at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
                                                                                                                                                   
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)                        
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)      
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)                    
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)                                  
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)                    
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)                          
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:256)                  
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317
)                                                                                                                                                  
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309
)                                                                                                                                                  
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)                            
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:97)                                 
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)                           
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:249)                
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:238)                
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)                   
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)                    
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:663)                                      
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:596)                              
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)                          
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)                                  
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)                                                   
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)                                   
Caused by: com.google.common.util.concurrent.ExecutionError: com.google.common.util.concurrent.ExecutionError: com.google.common.util.concurrent.Ex
ecutionError: com.google.common.util.concurrent.ExecutionError: com.google.common.util.concurrent.ExecutionError: com.google.common.util.concurrent
.ExecutionError: java.lang.UnsupportedClassVersionError: org/eclipse/core/runtime/OperationCanceledException has been compiled by a more recent ver
sion of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0                
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2199)                                                                    
        at com.google.common.cache.LocalCache.get(LocalCache.java:3934)                                                                            
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938)                                                                      
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821)                                                          
        at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4827)                                                 
        at com.google.inject.internal.FailableCache.get(FailableCache.java:48)                                                                     
        at com.google.inject.internal.ConstructorInjectorStore.get(ConstructorInjectorStore.java:50)                                               
        at com.google.inject.internal.ConstructorBindingImpl.initialize(ConstructorBindingImpl.java:136)                                           
        at com.google.inject.internal.InjectorImpl.initializeJitBinding(InjectorImpl.java:547)                                                     
        at com.google.inject.internal.InjectorImpl.createJustInTimeBinding(InjectorImpl.java:884)                                                  
        at com.google.inject.internal.InjectorImpl.createJustInTimeBindingRecursive(InjectorImpl.java:805)                                         
        at com.google.inject.internal.InjectorImpl.getJustInTimeBinding(InjectorImpl.java:282)                                                     
        at com.google.inject.internal.InjectorImpl.getBindingOrThrow(InjectorImpl.java:214)                                                        
        at com.google.inject.internal.InjectorImpl.getProviderOrThrow(InjectorImpl.java:1006)                                                      
        at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1038)                                                             
        at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1001)                                                             
        at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1051)                                                             
        at org.xtext.gradle.builder.XtextGradleBuilder.<init>(XtextGradleBuilder.java:88)                                                          
        at org.xtext.gradle.builder.XtextGradleBuilderFactory.get(XtextGradleBuilderFactory.java:14)                                               
        at org.xtext.gradle.tasks.internal.IncrementalXtextBuilderProvider.createBuilder(IncrementalXtextBuilderProvider.java:77)                  
        at org.xtext.gradle.tasks.internal.IncrementalXtextBuilderProvider.getBuilder(IncrementalXtextBuilderProvider.java:37)                     
        at org.xtext.gradle.tasks.XtextGenerate.initializeBuilder(XtextGenerate.java:380)                                                          
        at org.xtext.gradle.tasks.XtextGenerate.generate(XtextGenerate.java:163)                                                                   
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)                                                                       
        at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:50)                              
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)                                      
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)                                      
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:124)                           
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317
)                                                                                                                                                  
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309
)                                                                                                                                                  
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)                            
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:97)                                 
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)                           
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:113)                   
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:95)                   
        ... 29 more                                                                                                                                
```

**Comment by cdietrich** [comment]
see discussions in https://github.com/eclipse/xtext/issues/1976

**Comment by oehme** [comment]
Workaround till the plugin adds the BOM automatically:

```
configurations.all {
    if (name.contains("Tooling")) {
        dependencies {
            add(name, "org.eclipse.xtend:org.eclipse.xtend.core:$xtextVersion"))
            add(name, platform("org.eclipse.xtext:xtext-dev-bom:$xtextVersion"))
        }
    }
}
```

**Comment by kuniss** [comment]
@oehme How this workaround could look like for Gradle 4? 
I guess, the "platform" concept had been introduced at a later Gradle version. Unfortunately, we are stack to version 4 because Buildship had not finished https://github.com/eclipse/buildship/pull/988 yet.
Thanks for any hint.

(But the problem is the same for ...)

**Comment by cdietrich** [comment]
There should be the way to use explicit versions as you can find in a few of the 100 comments in the Xtext issue

**Comment by oehme** [comment]
@kuniss you can use `resolutionStrategy` instead, like @cdietrich did [here](https://github.com/eclipse/xtext/issues/1976#issuecomment-862141814).

**Comment by kuniss** [comment]
> 
> 
> @kuniss you can use `resolutionStrategy` instead, like @cdietrich did [here](https://github.com/eclipse/xtext/issues/1976#issuecomment-862141814).

Worked well for me. 🤝

**Comment by oehme** [comment]
[Version 2.0.9](https://plugins.gradle.org/plugin/org.xtext.builder/2.0.9) of the plugin fixes this.
