### ISSUE TITLE
Request support for android data binding

### ISSUE THREAD

**Issue by Buggaboo** [xtext/xtext-gradle-plugin#39]
Right now, the way to build an android project with data binding on [this branch](https://github.com/Buggaboo/Xtendroid/tree/v0.13_data_binding), requires multiple steps.

1. Transpile xtend without referring to the generated java files.
i.e. out comment ...DataBindingLayout...Binding.java in the xtend code,
e.g. so xtend won't fail due to the missing yet-to-be-generated
java files.
2. Build with: `./gradlew :Quotes:build`
3. Make the out commented lines active again.
4. Build again with `./gradlew :Quotes:build`

For every build, you need to repeat these four steps then `./gradlew :Quotes:clean`.
Yes, this is a pain in the ass.

If I attempt to build again, after those steps I mentioned without cleaning (e.g. `./gradlew :Quotes:clean`), I get this gradle NPE:

```

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':Quotes:compileDebugJavaWithJavac'.
> java.lang.NullPointerException (no error message)

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':Quotes:compileDebugJavaWithJavac'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:62)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:210)
	at com.google.common.collect.Iterables.filter(Iterables.java:584)
	at org.eclipse.xtext.xbase.lib.IterableExtensions.filter(IterableExtensions.java:253)
	at org.xtext.gradle.tasks.XtextGenerate$4.apply(XtextGenerate.java:376)
	at org.xtext.gradle.tasks.XtextGenerate$4.apply(XtextGenerate.java:366)
	at org.eclipse.xtext.xbase.lib.ObjectExtensions.operator_doubleArrow(ObjectExtensions.java:139)
	at org.xtext.gradle.tasks.XtextGenerate.installDebugInfo(XtextGenerate.java:409)
	at org.xtext.gradle.android.XtextAndroidBuilderPlugin$6$2.execute(XtextAndroidBuilderPlugin.java:188)
	at org.xtext.gradle.android.XtextAndroidBuilderPlugin$6$2.execute(XtextAndroidBuilderPlugin.java:185)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:585)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:568)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
	... 14 more
```

I think we should move the data binding code generation ahead of the Xtend transpilation process.

I tried to study how Kotlin does it, but I haven't found anything yet.

**Comment by Buggaboo** [comment]
There are some ways to determine if an android project is using databinding.

1. First of all, `build.gradle` of course. `dataBinding.enabled = true`.
2. To determine what is going to be generated: `res/layout/some_layout.xml` will generate `SomeLayoutBinding.java` and other additional classes.
```xml
<?xml version="1.0" encoding="utf-8"?>
<layout xmlns:android="http://schemas.android.com/apk/res/android">
...
```

**Comment by oehme** [comment]
@Buggaboo there's no need to look into any files, everything we do is done against the android-gradle APIs.

**Comment by Buggaboo** [comment]
Ow, okay, in that case, we're using >2.0 (alpha).

**Comment by Buggaboo** [comment]
After some digging, I found out that the `dataBinding` classes (e.g. `MainActivityBinding.java`, `BR.java`) are being generated after Xtend parses the available class references.

So if we can move these tasks before Xtend's tasks, then dataBinding will go just fine.

The tasks are:
* :Quotes:prepareComAndroidDatabindingAdapters10Rc3Library
* :Quotes:prepareComAndroidDatabindingLibrary10Rc3Library
* :Quotes:dataBindingProcessLayoutsDebug
* :Quotes:dataBindingExportBuildInfoDebug
* :Quotes:dataBindingProcessLayoutsRelease
* :Quotes:dataBindingExportBuildInfoRelease




```
Parallel execution is an incubating feature.
:Quotes:preBuild
:Xtendroid:preBuild
:Quotes:preBuild UP-TO-DATE
:Xtendroid:preBuild UP-TO-DATE
:Xtendroid:preReleaseBuild UP-TO-DATE
:Quotes:preDebugBuild UP-TO-DATE
:Xtendroid:compileReleaseNdk UP-TO-DATE
:Quotes:checkDebugManifest
:Xtendroid:compileLint
:Quotes:preReleaseBuild UP-TO-DATE
:Xtendroid:copyReleaseLint
:Quotes:generateDebugResValues
:Xtendroid:copyReleaseLint UP-TO-DATE
:Xtendroid:checkReleaseManifest
:Xtendroid:preDebugAndroidTestBuild UP-TO-DATE
:Xtendroid:preDebugBuild UP-TO-DATE
:Xtendroid:preDebugUnitTestBuild UP-TO-DATE
:Quotes:generateDebugResValues UP-TO-DATE
:Quotes:generateDebugBuildConfig
:Xtendroid:preReleaseUnitTestBuild UP-TO-DATE
:Xtendroid:prepareComAndroidSupportAppcompatV72311Library
:Quotes:generateDebugBuildConfig UP-TO-DATE
:Quotes:generateDebugAssets UP-TO-DATE
:Quotes:compileDebugNdk UP-TO-DATE
:Quotes:processDebugJavaRes UP-TO-DATE
:Quotes:validateDebugSigning
:Quotes:checkReleaseManifest
:Quotes:generateReleaseResValues UP-TO-DATE
:Quotes:generateReleaseBuildConfig UP-TO-DATE
:Quotes:generateReleaseAssets UP-TO-DATE
:Quotes:compileReleaseNdk UP-TO-DATE
:Quotes:processReleaseJavaRes
:Xtendroid:prepareComAndroidSupportAppcompatV72311Library UP-TO-DATE
:Xtendroid:prepareComAndroidSupportSupportV42311Library
:Quotes:processReleaseJavaRes UP-TO-DATE
:Quotes:compileLint
:Quotes:preDebugUnitTestBuild UP-TO-DATE
:Xtendroid:prepareComAndroidSupportSupportV42311Library UP-TO-DATE
:Quotes:prepareDebugUnitTestDependencies
:Xtendroid:prepareReleaseDependencies
:Quotes:processDebugUnitTestJavaRes UP-TO-DATE
:Xtendroid:compileReleaseAidl
:Quotes:mockableAndroidJar UP-TO-DATE
:Quotes:preReleaseUnitTestBuild UP-TO-DATE
:Quotes:prepareReleaseUnitTestDependencies
:Quotes:processReleaseUnitTestJavaRes UP-TO-DATE
:Xtendroid:compileReleaseAidl UP-TO-DATE
:Xtendroid:compileReleaseRenderscript UP-TO-DATE
:Xtendroid:generateReleaseBuildConfig UP-TO-DATE
:Xtendroid:generateReleaseAssets UP-TO-DATE
:Xtendroid:mergeReleaseAssets UP-TO-DATE
:Xtendroid:generateReleaseResValues UP-TO-DATE
:Xtendroid:generateReleaseResources UP-TO-DATE
:Xtendroid:mergeReleaseResources UP-TO-DATE
:Xtendroid:processReleaseManifest UP-TO-DATE
:Xtendroid:processReleaseResources UP-TO-DATE
:Xtendroid:generateReleaseXtext UP-TO-DATE
:Xtendroid:generateReleaseSources UP-TO-DATE
:Xtendroid:compileReleaseJavaWithJavac UP-TO-DATE
:Xtendroid:extractReleaseAnnotations UP-TO-DATE
:Xtendroid:mergeReleaseProguardFiles UP-TO-DATE
:Xtendroid:packageReleaseRenderscript UP-TO-DATE
:Xtendroid:packageReleaseResources UP-TO-DATE
:Xtendroid:processReleaseJavaRes UP-TO-DATE
:Xtendroid:transformResourcesWithMergeJavaResForRelease UP-TO-DATE
:Xtendroid:transformClassesAndResourcesWithSyncLibJarsForRelease UP-TO-DATE
:Xtendroid:mergeReleaseJniLibFolders UP-TO-DATE
:Xtendroid:transformNative_libsWithMergeJniLibsForRelease UP-TO-DATE
:Xtendroid:transformNative_libsWithSyncJniLibsForRelease UP-TO-DATE
:Xtendroid:bundleRelease UP-TO-DATE
:Quotes:prepareComAndroidDatabindingAdapters10Rc3Library UP-TO-DATE
:Quotes:prepareComAndroidDatabindingLibrary10Rc3Library UP-TO-DATE
:Quotes:prepareComAndroidSupportAppcompatV72311Library UP-TO-DATE
:Quotes:prepareComAndroidSupportSupportV42311Library UP-TO-DATE
:Quotes:prepareXtendroidXtendroidUnspecifiedLibrary UP-TO-DATE
:Quotes:prepareDebugDependencies
:Quotes:compileDebugAidl UP-TO-DATE
:Quotes:compileDebugRenderscript UP-TO-DATE
:Quotes:generateDebugResources UP-TO-DATE
:Quotes:mergeDebugResources UP-TO-DATE
:Quotes:dataBindingProcessLayoutsDebug UP-TO-DATE
:Quotes:dataBindingExportBuildInfoDebug
:Quotes:mergeDebugAssets UP-TO-DATE
:Quotes:processDebugManifest UP-TO-DATE
:Quotes:processDebugResources UP-TO-DATE
:Quotes:generateDebugXtext UP-TO-DATE
:Quotes:generateDebugSources
:Quotes:compileDebugJavaWithJavac
:Quotes:compileDebugSources
:Quotes:transformClassesWithDexForDebug UP-TO-DATE
:Quotes:mergeDebugJniLibFolders UP-TO-DATE
:Quotes:transformNative_libsWithMergeJniLibsForDebug UP-TO-DATE
:Quotes:transformResourcesWithMergeJavaResForDebug UP-TO-DATE
:Quotes:packageDebug UP-TO-DATE
:Quotes:zipalignDebug UP-TO-DATE
:Quotes:assembleDebug
:Quotes:prepareReleaseDependencies
:Quotes:compileReleaseAidl UP-TO-DATE
:Quotes:compileReleaseRenderscript UP-TO-DATE
:Quotes:generateReleaseResources UP-TO-DATE
:Quotes:mergeReleaseResources UP-TO-DATE
:Quotes:dataBindingProcessLayoutsRelease UP-TO-DATE
:Quotes:dataBindingExportBuildInfoRelease
:Quotes:mergeReleaseAssets UP-TO-DATE
:Quotes:processReleaseManifest UP-TO-DATE
:Quotes:processReleaseResources UP-TO-DATE
:Quotes:generateReleaseXtext UP-TO-DATE
:Quotes:generateReleaseSources
:Quotes:compileReleaseJavaWithJavac
:Quotes:compileReleaseSources
:Quotes:lintVitalRelease
:Quotes:transformClassesWithDexForRelease UP-TO-DATE
:Quotes:mergeReleaseJniLibFolders UP-TO-DATE
:Quotes:transformNative_libsWithMergeJniLibsForRelease UP-TO-DATE
:Quotes:transformResourcesWithMergeJavaResForRelease UP-TO-DATE
:Quotes:packageRelease UP-TO-DATE
:Quotes:assembleRelease
:Quotes:assemble
:Quotes:lint
Wrote HTML report to file:///Users/jasmsison/Documents/git-repositories/Xtendroid/examples/Quotes/build/outputs/lint-results.html
Wrote XML report to file:///Users/jasmsison/Documents/git-repositories/Xtendroid/examples/Quotes/build/outputs/lint-results.xml
Lint found 0 errors and 3 warnings
:Quotes:compileDebugUnitTestJavaWithJavac UP-TO-DATE
:Quotes:compileDebugUnitTestSources UP-TO-DATE
:Quotes:assembleDebugUnitTest UP-TO-DATE
:Quotes:testDebugUnitTest UP-TO-DATE
:Quotes:compileReleaseUnitTestJavaWithJavac UP-TO-DATE
:Quotes:compileReleaseUnitTestSources UP-TO-DATE
:Quotes:assembleReleaseUnitTest UP-TO-DATE
:Quotes:testReleaseUnitTest UP-TO-DATE
:Quotes:test UP-TO-DATE
:Quotes:check
:Quotes:build

BUILD SUCCESSFUL

Total time: 5.402 secs
```

**Comment by oehme** [comment]
I checked the API in both `1.5` and `2.0` and the databinding tasks are private API. This means I cannot reference them without risking breaking changes in future versions. Judging by the comments in the Android plugin, they will be removed in the future (and replaced with something else).

As a workaround you can of course set up the task dependency yourself. It might break with future Android versions, though:

```
project.afterEvaluate {
  android.applicationVariants.all {variant ->
    task("generate${variant.name}Xtext").dependsOn(
      "dataBindingProcessLayouts${variant.name}", 
      "dataBindingExportBuildInfo${variant.name}"
    )
  } 
}

**Comment by Buggaboo** [comment]
I found out the hard way that there is a cyclic dependency between:
* `"generate${variantName}Sources"`
* `"generate${variantName}Xtext"`

I found out by adding the following to the `build.gradle` file:
```gradle
// Circular dependency!
project.afterEvaluate {
  android.applicationVariants.all { variant ->

    // force ordering on the tasks
    def variantName = variant.name.capitalize()
    tasks["generate${variantName}Xtext"].mustRunAfter /*dependsOn*/ tasks["compile${variantName}JavaWithJavac"]

    // add srcDir, depending on the variant
    def sourceDir = "${buildDir}/generated/source/xtend/${variant.dirName}"
    variant.addJavaSourceFoldersToModel new File(sourceDir)
  }
}

// Debugging!
project.tasks.whenTaskAdded { task ->
  doLast {
    println task.name
    println file("build/intermediates/classes/debug/com/example/quotes/databinding/MainActivityBinding.java").exists()
    println file("build/intermediates/classes/debug/com/android/databinding/library/baseAdapters/BR.java").exists()
    println file("build/intermediates/classes/debug/com/example/quotes/BR.java").exists()
    println file("build/intermediates/classes/release/com/example/quotes/databinding/MainActivityBinding.java").exists()
    println file("build/intermediates/classes/release/com/android/databinding/library/baseAdapters/BR.java").exists()
    println file("build/intermediates/classes/release/com/example/quotes/BR.java").exists()
  }
}
```

Any ideas on how to break the cycle? @oehme

**Comment by oehme** [comment]
I don't get what you are trying to do. Xtend must run **before** the Java compiler, not after.

**Comment by Buggaboo** [comment]
That's the crazy thing, `"compile${variantName}JavaWithJavac"` generates the `<layout>Binding.java` files.

```
:Quotes:generateDebugXtext
generateDebugXtext
false
false
false
false
false
false
:Quotes:generateDebugSources
generateDebugSources
false
false
false
false
false
false
:Quotes:compileDebugJavaWithJavac
compileDebugJavaWithJavac
true <- The files generated by the databinding mechanism, only exist after :Quotes:generate<Variant>Xtext
true
true
false
false
false
:Quotes:compileDebugSources
compileDebugSources
true
true
true
false
false
false
...
```

**Comment by oehme** [comment]
In that case, it seems that databinding is based on Java Annotation Processing. Xtend is not compatible with APT. So there's unfortunately nothing I can do on the Gradle side to make it work.

**Comment by Buggaboo** [comment]
I tried adding the following to my `build.gradle`:
```gradle
// Clone a task, then run it to break the cyclic dependency
project.afterEvaluate {
    android.applicationVariants.all { variant ->
        def variantName = variant.name.capitalize()
        project.tasks.create(name: "preProcess${variantName}DataBinding", /*dependsOn: "process${variantName}Resources",*/ type: org.gradle.api.tasks.compile.JavaCompile) {
            println 'Attempting to generate data binding classes and compile them first'
            mustRunAfter "process${variantName}Resources"
            dependsOn "process${variantName}Resources"
        }
    }
}
```
So far, no cigar.

I'm not gonna spend any more time on this. Unless someone has a brilliant idea on how to break the cycle. In any case, thanks Stefan @oehme
