### ISSUE TITLE
ClassNotFoundException: com.google.common.collect.Lists

### ISSUE THREAD

**Issue by kthoms** [xtext/xtext-gradle-plugin#74]
I just installed a new Xtext devenv with Oomph and got the following error:
```
Synchronize Gradle projects with workspace failed due to an error in the referenced Gradle build.
Could not run build action using Gradle distribution 'https://services.gradle.org/distributions-snapshots/gradle-3.3-20161123000010+0000-bin.zip'.

Build file '/Users/thoms/temp/xtext-dev/git/xtext-idea/build.gradle' line: 21
A problem occurred evaluating root project 'xtext-idea'.
Failed to apply plugin [class 'org.xtext.gradle.XtextBuilderPlugin']
Could not create an instance of type org.xtext.gradle.tasks.XtextExtension_Decorated.
[...]
Caused by: org.gradle.internal.reflect.ObjectInstantiationException: Could not create an instance of type org.xtext.gradle.tasks.XtextExtension_Decorated.
	at org.gradle.internal.reflect.DirectInstantiator.newInstance(DirectInstantiator.java:44)
	at org.gradle.api.internal.ClassGeneratorBackedInstantiator.newInstance(ClassGeneratorBackedInstantiator.java:36)
	at org.gradle.api.internal.plugins.DefaultConvention.create(DefaultConvention.java:103)
	at org.xtext.gradle.XtextBuilderPlugin.apply(XtextBuilderPlugin.java:77)
[...]
Caused by: java.lang.NoClassDefFoundError: com/google/common/collect/Lists
	at org.xtext.gradle.tasks.XtextExtension.<init>(XtextExtension.java:64)
	at org.xtext.gradle.tasks.XtextExtension_Decorated.<init>(Unknown Source)
	at org.gradle.internal.reflect.DirectInstantiator.newInstance(DirectInstantiator.java:42)
	... 133 more
Caused by: java.lang.ClassNotFoundException: com.google.common.collect.Lists
	... 136 more
```

Full log:
[GradlePluginNCDFError.txt](https://github.com/xtext/xtext-gradle-plugin/files/701465/GradlePluginNCDFError.txt)

**Comment by oehme** [comment]
The plugin depends on Guava, so the only way this could happen is if your build somehow excluded guava from the plugin classpath. @spoenemann any idea how that could have happened? Can you reproduce?

**Comment by kthoms** [comment]
For me it is reproducible with a fresh clone of xtext-idea.
```
git clone https://github.com/eclipse/xtext-idea.git
cd xtext-idea
./gradlew tasks
```

**Comment by spoenemann** [comment]
When I execute exactly those lines, everything works as expected. @kthoms is your Gradle cache broken?

The classpath is configured here:
https://github.com/eclipse/xtext-idea/blob/master/gradle/bootstrap-setup.gradle
There's no configuration regarding Guava.

Here's the dependency output:
```
xtendCompiler - Bootstrap dependencies for the Xtend compiler
+--- org.eclipse.xtend:org.eclipse.xtend.core:2.11.0-SNAPSHOT
|    +--- org.eclipse.xtext:org.eclipse.xtext.xbase:2.11.0-SNAPSHOT
|    |    \--- org.eclipse.xtext:org.eclipse.xtext.common.types:2.11.0-SNAPSHOT
|    |         +--- org.eclipse.xtext:org.eclipse.xtext:2.11.0-SNAPSHOT
|    |         |    +--- org.eclipse.xtext:org.eclipse.xtext.util:2.11.0-SNAPSHOT
|    |         |    |    +--- org.eclipse.xtend:org.eclipse.xtend.lib:2.11.0-SNAPSHOT
|    |         |    |    |    +--- org.eclipse.xtext:org.eclipse.xtext.xbase.lib:2.11.0-SNAPSHOT
|    |         |    |    |    |    \--- com.google.guava:guava:[14.0,19) -> 18.0
|    |         |    |    |    \--- org.eclipse.xtend:org.eclipse.xtend.lib.macro:2.11.0-SNAPSHOT
|    |         |    |    |         \--- org.eclipse.xtext:org.eclipse.xtext.xbase.lib:2.11.0-SNAPSHOT (*)
|    |         |    |    +--- log4j:log4j:1.2.16
|    |         |    |    +--- org.eclipse.emf:org.eclipse.emf.common:[2.10.1,3) -> 2.12.0
|    |         |    |    +--- org.eclipse.emf:org.eclipse.emf.ecore:[2.10.2,3) -> 2.12.0
|    |         |    |    \--- com.google.inject:guice:3.0
|    |         |    |         +--- javax.inject:javax.inject:1
|    |         |    |         \--- aopalliance:aopalliance:1.0
|    |         |    +--- org.eclipse.xtend:org.eclipse.xtend.lib:2.11.0-SNAPSHOT (*)
|    |         |    +--- log4j:log4j:1.2.16
|    |         |    +--- org.eclipse.equinox:org.eclipse.equinox.common:3.6.0
|    |         |    +--- org.eclipse.emf:org.eclipse.emf.common:[2.10.1,3) -> 2.12.0
|    |         |    +--- org.eclipse.emf:org.eclipse.emf.ecore.xmi:[2.10.2,3) -> 2.12.0
|    |         |    +--- com.google.inject:guice:3.0 (*)
|    |         |    \--- org.antlr:antlr-runtime:3.2
|    |         \--- org.ow2.asm:asm-commons:5.0.1
|    |              \--- org.ow2.asm:asm-tree:5.0.1
|    |                   \--- org.ow2.asm:asm:5.0.1
|    \--- org.eclipse.jdt:org.eclipse.jdt.core:[3.6.0,4) -> 3.12.2
|         +--- org.eclipse.platform:org.eclipse.core.resources:[3.3.0,4.0.0) -> 3.11.1
|         |    +--- org.eclipse.platform:org.eclipse.core.expressions:[3.2.0,4.0.0) -> 3.5.100
|         |    |    \--- org.eclipse.platform:org.eclipse.core.runtime:[3.3.0,4.0.0) -> 3.12.0
|         |    |         +--- org.eclipse.platform:org.eclipse.osgi:[3.7.0,4.0.0) -> 3.11.2
|         |    |         +--- org.eclipse.platform:org.eclipse.equinox.common:[3.8.0,4.0.0) -> 3.8.0
|         |    |         +--- org.eclipse.platform:org.eclipse.core.jobs:[3.2.0,4.0.0) -> 3.8.0
|         |    |         |    \--- org.eclipse.platform:org.eclipse.equinox.common:[3.8.0,4.0.0) -> 3.8.0
|         |    |         +--- org.eclipse.platform:org.eclipse.equinox.registry:[3.4.0,4.0.0) -> 3.6.100
|         |    |         |    \--- org.eclipse.platform:org.eclipse.equinox.common:[3.7.0,4.0.0) -> 3.8.0
|         |    |         +--- org.eclipse.platform:org.eclipse.equinox.preferences:[3.4.0,4.0.0) -> 3.6.1
|         |    |         |    \--- org.eclipse.platform:org.eclipse.equinox.common:[3.2.0,4.0.0) -> 3.8.0
|         |    |         +--- org.eclipse.platform:org.eclipse.core.contenttype:[3.3.0,4.0.0) -> 3.5.100
|         |    |         |    +--- org.eclipse.platform:org.eclipse.equinox.preferences:[3.2.0,4.0.0) -> 3.6.1 (*)
|         |    |         |    +--- org.eclipse.platform:org.eclipse.equinox.registry:[3.2.0,4.0.0) -> 3.6.100 (*)
|         |    |         |    \--- org.eclipse.platform:org.eclipse.equinox.common:[3.2.0,4.0.0) -> 3.8.0
|         |    |         \--- org.eclipse.platform:org.eclipse.equinox.app:[1.0.0,) -> 1.3.400
|         |    |              +--- org.eclipse.platform:org.eclipse.equinox.registry:[3.4.0,4.0.0) -> 3.6.100 (*)
|         |    |              \--- org.eclipse.platform:org.eclipse.equinox.common:[3.2.0,4.0.0) -> 3.8.0
|         |    +--- org.eclipse.platform:org.eclipse.core.filesystem:[1.3.0,2.0.0) -> 1.6.1
|         |    |    +--- org.eclipse.platform:org.eclipse.equinox.common:[3.2.0,4.0.0) -> 3.8.0
|         |    |    +--- org.eclipse.platform:org.eclipse.equinox.registry:[3.2.0,4.0.0) -> 3.6.100 (*)
|         |    |    \--- org.eclipse.platform:org.eclipse.osgi:[3.2.0,4.0.0) -> 3.11.2
|         |    \--- org.eclipse.platform:org.eclipse.core.runtime:[3.12.0,4.0.0) -> 3.12.0 (*)
|         +--- org.eclipse.platform:org.eclipse.core.runtime:[3.3.0,4.0.0) -> 3.12.0 (*)
|         +--- org.eclipse.platform:org.eclipse.core.filesystem:[1.0.0,2.0.0) -> 1.6.1 (*)
|         \--- org.eclipse.platform:org.eclipse.text:[3.1.0,4.0.0) -> 3.6.0
|              +--- org.eclipse.platform:org.eclipse.core.commands:[3.5.0,4.0.0) -> 3.8.0
|              |    \--- org.eclipse.platform:org.eclipse.equinox.common:[3.2.0,4.0.0) -> 3.8.0
|              \--- org.eclipse.platform:org.eclipse.equinox.common:[3.5.0,4.0.0) -> 3.8.0
+--- org.eclipse.xtext:org.eclipse.xtext.smap:2.11.0-SNAPSHOT
|    \--- org.eclipse.xtext:org.eclipse.xtext:2.11.0-SNAPSHOT (*)
\--- org.xtext:xtext-gradle-builder:1.0.15
     +--- com.google.guava:guava:18.0
     +--- org.eclipse.xtend:org.eclipse.xtend.lib:2.9.0 -> 2.11.0-SNAPSHOT (*)
     +--- org.eclipse.xtext:org.eclipse.xtext:2.9.0 -> 2.11.0-SNAPSHOT (*)
     +--- org.eclipse.xtext:org.eclipse.xtext.java:2.9.0 -> 2.11.0-SNAPSHOT
     |    +--- org.eclipse.xtext:org.eclipse.xtext.common.types:2.11.0-SNAPSHOT (*)
     |    \--- org.eclipse.jdt:org.eclipse.jdt.core:[3.6.0,4) -> 3.12.2 (*)
     +--- org.eclipse.xtext:org.eclipse.xtext.xbase:2.9.0 -> 2.11.0-SNAPSHOT (*)
     +--- org.eclipse.xtext:org.eclipse.xtext.smap:2.9.0 -> 2.11.0-SNAPSHOT (*)
     \--- org.xtext:xtext-gradle-protocol:1.0.15
          \--- com.google.guava:guava:18.0

(*) - dependencies omitted (listed previously)
```

**Comment by spoenemann** [comment]
I refreshed the Xtend compiler classpath by running the xtend-bootstrap build job:
http://services.typefox.io/open-source/jenkins/job/xtend-bootstrap/

@kthoms could you check again with `--refresh-dependencies`?

**Comment by kthoms** [comment]
@spoenemann Indeed, this helped. Sorry for the noise.
