### ISSUE TITLE
1.0.17 does not work with xtext 2.10.0

### ISSUE THREAD

**Issue by tmtron** [xtext/xtext-gradle-plugin#76]
Related to #67:  
after upgrading from [1.0.16](https://github.com/xtext/xtext-gradle-plugin/releases/tag/1.0.16) to [1.0.17 ](https://github.com/xtext/xtext-gradle-plugin/releases/tag/1.0.17) (and removing my jdt.core dependency), the build failed.  
My app `build.gradle` has specified this xtext version:
```gradle
xtext {
    version = "2.10.0"
```

```bash
./gradlew clean build --stacktrace
```
(stripped) stacktrace:
```
* What went wrong:
Execution failed for task ':app:generateDebugXtext'.
> -1

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:generateDebugXtext'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:84)
...
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
        at org.eclipse.jdt.internal.compiler.parser.Parser.consumeInternalCompilationUnitWithTypes(Parser.java:4631)
        at org.eclipse.jdt.internal.compiler.parser.Parser.consumeRule(Parser.java:6085)
        at org.eclipse.jdt.internal.compiler.parser.Parser.parse(Parser.java:11035)
        at org.eclipse.jdt.internal.compiler.parser.Parser.parse(Parser.java:11283)
        at org.eclipse.jdt.internal.compiler.parser.Parser.parse(Parser.java:11240)
        at org.eclipse.jdt.internal.compiler.parser.Parser.dietParse(Parser.java:9660)
        at org.eclipse.xtext.java.resource.JavaDerivedStateComputer.installStubs(JavaDerivedStateComputer.java:90)
        at org.eclipse.xtext.java.resource.JavaResource$3.apply(JavaResource.java:129)
        at org.eclipse.xtext.java.resource.JavaResource.initializing(JavaResource.java:150)
        at org.eclipse.xtext.java.resource.JavaResource.installStubs(JavaResource.java:133)
        at org.eclipse.xtext.java.resource.JavaResourceDescriptionManager.getResourceDescription(JavaResourceDescriptionManager.java:39)
        at org.eclipse.xtext.build.Indexer.addToIndex(Indexer.java:347)
        at org.eclipse.xtext.build.Indexer$6.apply(Indexer.java:330)
        at org.eclipse.xtext.build.Indexer$6.apply(Indexer.java:1)
        at org.eclipse.xtext.build.ClusteringStorageAwareResourceLoader$2.apply(ClusteringStorageAwareResourceLoader.java:91)
        at org.eclipse.xtext.build.ClusteringStorageAwareResourceLoader$2.apply(ClusteringStorageAwareResourceLoader.java:1)
        at org.eclipse.xtext.xbase.lib.internal.FunctionDelegate.apply(FunctionDelegate.java:42)
        at com.google.common.collect.Lists$TransformingRandomAccessList$1.transform(Lists.java:640)
        at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
        at com.google.common.collect.Iterables.addAll(Iterables.java:350)
        at org.eclipse.xtext.build.ClusteringStorageAwareResourceLoader.executeClustered(ClusteringStorageAwareResourceLoader.java:95)
        at org.eclipse.xtext.build.BuildContext.executeClustered(BuildContext.java:62)
        at org.eclipse.xtext.build.Indexer.getDeltasForChangedResources(Indexer.java:333)
        at org.eclipse.xtext.build.Indexer.computeAndIndexAffected(Indexer.java:238)
        at org.eclipse.xtext.build.IncrementalBuilder$InternalStatefulIncrementalBuilder.launch(IncrementalBuilder.java:207)
        at org.eclipse.xtext.build.IncrementalBuilder.build(IncrementalBuilder.java:468)
        at org.eclipse.xtext.build.IncrementalBuilder.build(IncrementalBuilder.java:449)
        at org.xtext.gradle.builder.XtextGradleBuilder.doBuild(XtextGradleBuilder.java:360)
        at org.xtext.gradle.builder.XtextGradleBuilder.build(XtextGradleBuilder.java:206)
        at org.xtext.gradle.tasks.XtextGenerate.generate(XtextGenerate.java:149)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$IncrementalTaskAction.doExecute(DefaultTaskClassInfoStore.java:163)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:123)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:95)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:76)
        ... 70 more
```

Note: this is not really an issue for me, since I can simply update the xtext version:
```gradle
xtext {
    version = "2.11.0.RC1"
```
and then it works with [1.0.16](https://github.com/xtext/xtext-gradle-plugin/releases/tag/1.0.16) and  [1.0.17 ](https://github.com/xtext/xtext-gradle-plugin/releases/tag/1.0.17)

**Comment by oehme** [comment]
I'm afraid that's a bug in how Xtext 2.10 calls JDT, so nothing we can fix from the plugin side.
