### ISSUE TITLE
java.lang.NullPointerException during generateTestXtext

### ISSUE THREAD

**Issue by dantonini** [xtext/xtext-gradle-plugin#82]
As suggested by Christian Dietrich in this post
https://groups.google.com/forum/#!msg/xtend-lang/zPxnWX30Ndk/2DuXXdwhAgAJ

I'm not able to reprocude the problem anymore, maybe due to a gradle clean task.

Here is the full stacktrace

:livetable:classes UP-TO-DATE
:livetable:generateTestXtext
WARNING:The constructor TableSnap(String, Connection, String) is deprecated (.... livebase/livetable/src/test/java/com/fhoster/livetable/servant/otf/OtfSearchTest.xtend line : 346 column : 15)
WARNING:GroupingField is a raw type. References to generic type GroupingField<T> should be parameterized (.... livebase/livetable/src/test/java/com/fhoster/livetable/servant/otf/OTFBugzTest.xtend line : 54 column : 86)
WARNING:Null-safe call of primitive-valued feature groupId, default value 0 will be used (.... livebase/livetable/src/test/java/com/fhoster/livetable/servant/otf/OTFBugzTest.xtend line : 58 column : 8)
WARNING:GroupingField is a raw type. References to generic type GroupingField<T> should be parameterized (.... livebase/livetable/src/test/java/com/fhoster/livetable/servant/otf/OTFBugzTest.xtend line : 58 column : 28)
WARNING:Null-safe call of primitive-valued feature groupId, default value 0 will be used (.... livebase/livetable/src/test/java/com/fhoster/livetable/servant/otf/OTFBugzTest.xtend line : 63 column : 8)
WARNING:GroupingField is a raw type. References to generic type GroupingField<T> should be parameterized (.... livebase/livetable/src/test/java/com/fhoster/livetable/servant/otf/OTFBugzTest.xtend line : 63 column : 28)
WARNING:Null-safe call of primitive-valued feature groupId, default value 0 will be used (.... livebase/livetable/src/test/java/com/fhoster/livetable/servant/otf/OTFBugzTest.xtend line : 63 column : 54)
WARNING:GroupingField is a raw type. References to generic type GroupingField<T> should be parameterized (.... livebase/livetable/src/test/java/com/fhoster/livetable/servant/otf/OTFBugzTest.xtend line : 63 column : 73)
WARNING:Null-safe call of primitive-valued feature groupId, default value 0 will be used (.... livebase/livetable/src/test/java/com/fhoster/livetable/servant/otf/OTFBugzTest.xtend line : 67 column : 20)
WARNING:GroupingField is a raw type. References to generic type GroupingField<T> should be parameterized (.... livebase/livetable/src/test/java/com/fhoster/livetable/servant/otf/OTFBugzTest.xtend line : 67 column : 44)
WARNING:GroupingField is a raw type. References to generic type GroupingField<T> should be parameterized (.... livebase/livetable/src/test/java/com/fhoster/livetable/servant/otf/OTFBugzTest.xtend line : 84 column : 87)
WARNING:GroupingField is a raw type. References to generic type GroupingField<T> should be parameterized (.... livebase/livetable/src/test/java/com/fhoster/livetable/servant/otf/OTFBugzTest.xtend line : 91 column : 28)
WARNING:GroupingField is a raw type. References to generic type GroupingField<T> should be parameterized (.... livebase/livetable/src/test/java/com/fhoster/livetable/servant/otf/OTFBugzTest.xtend line : 95 column : 23)
WARNING:StatisticsField is a raw type. References to generic type StatisticsField<T> should be parameterized (.... livebase/livetable/src/test/java/com/fhoster/livetable/servant/otf/OTFBugzTest.xtend line : 134 column : 42)
WARNING:The method getHours() from the type Date is deprecated (.... livebase/livetable/src/test/java/com/fhoster/livetable/servant/otf/OTFServantTest.xtend line : 57 column : 49)
WARNING:The method getDate() from the type Date is deprecated (.... livebase/livetable/src/test/java/com/fhoster/livetable/servant/otf/OTFServantTest.xtend line : 81 column : 47)
WARNING:The value of the local variable a2s is not used (.... livebase/livetable/src/test/java/com/fhoster/livetable/servant/otf/OTFConfigurationTest.xtend line : 119 column : 7)
:livetable:generateTestXtext FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':livetable:generateTestXtext'.
> java.lang.NullPointerException (no error message)

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':livetable:generateTestXtext'.
Caused by: java.lang.NullPointerException
        at org.eclipse.jdt.internal.compiler.problem.ProblemHandler.handle(ProblemHandler.java:138)
        at org.eclipse.jdt.internal.compiler.problem.ProblemHandler.handle(ProblemHandler.java:217)
        at org.eclipse.jdt.internal.compiler.problem.ProblemReporter.handle(ProblemReporter.java:2366)
        at org.eclipse.jdt.internal.compiler.problem.ProblemReporter.rawTypeReference(ProblemReporter.java:7138)
        at org.eclipse.jdt.internal.compiler.ast.TypeReference.internalResolveType(TypeReference.java:500)
        at org.eclipse.jdt.internal.compiler.ast.TypeReference.resolveType(TypeReference.java:563)
        at org.eclipse.jdt.internal.compiler.ast.TypeReference.resolveType(TypeReference.java:559)
        at org.eclipse.jdt.internal.compiler.lookup.SourceTypeBinding.resolveTypesFor(SourceTypeBinding.java:1851)
        at org.eclipse.jdt.internal.compiler.lookup.SourceTypeBinding.methods(SourceTypeBinding.java:1464)
        at org.eclipse.jdt.internal.compiler.lookup.SourceTypeBinding.faultInTypesForFieldsAndMethods(SourceTypeBinding.java:852)
        at org.eclipse.jdt.internal.compiler.lookup.CompilationUnitScope.faultInTypes(CompilationUnitScope.java:450)
        at org.eclipse.jdt.internal.compiler.Compiler.process(Compiler.java:763)
        at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:470)
        at org.eclipse.xtext.java.resource.JavaDerivedStateComputer.installFull(JavaDerivedStateComputer.java:244)
        at org.eclipse.xtext.java.resource.JavaResource$4.apply(JavaResource.java:140)
        at org.eclipse.xtext.java.resource.JavaResource.initializing(JavaResource.java:150)
        at org.eclipse.xtext.java.resource.JavaResource.installFull(JavaResource.java:144)
        at org.eclipse.xtext.java.resource.JavaResource.getContents(JavaResource.java:113)
        at org.eclipse.xtext.build.IncrementalBuilder$InternalStatefulIncrementalBuilder$5.apply(IncrementalBuilder.java:242)
        at org.eclipse.xtext.build.IncrementalBuilder$InternalStatefulIncrementalBuilder$5.apply(IncrementalBuilder.java:1)
        at org.eclipse.xtext.build.ClusteringStorageAwareResourceLoader$2.apply(ClusteringStorageAwareResourceLoader.java:91)
        at org.eclipse.xtext.build.ClusteringStorageAwareResourceLoader$2.apply(ClusteringStorageAwareResourceLoader.java:1)
        at org.eclipse.xtext.xbase.lib.internal.FunctionDelegate.apply(FunctionDelegate.java:42)
        at com.google.common.collect.Lists$TransformingRandomAccessList$1.transform(Lists.java:640)
        at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
        at com.google.common.collect.Iterables.addAll(Iterables.java:350)
        at org.eclipse.xtext.build.ClusteringStorageAwareResourceLoader.executeClustered(ClusteringStorageAwareResourceLoader.java:95)
        at org.eclipse.xtext.build.BuildContext.executeClustered(BuildContext.java:62)
        at org.eclipse.xtext.build.IncrementalBuilder$InternalStatefulIncrementalBuilder.launch(IncrementalBuilder.java:268)
        at org.eclipse.xtext.build.IncrementalBuilder.build(IncrementalBuilder.java:468)
        at org.eclipse.xtext.build.IncrementalBuilder.build(IncrementalBuilder.java:449)
        at org.xtext.gradle.builder.XtextGradleBuilder.doBuild(XtextGradleBuilder.java:360)
        at org.xtext.gradle.builder.XtextGradleBuilder.build(XtextGradleBuilder.java:206)
        at org.xtext.gradle.tasks.XtextGenerate.generate(XtextGenerate.java:149)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.doExecute(AnnotationProcessingTaskFactory.java:245)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:221)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.execute(AnnotationProcessingTaskFactory.java:232)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:210)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        ... 68 more

**Comment by oehme** [comment]
The exception is coming from Xtext or JDT, so this is untelated to the Gradle plugin. I remember this problem from Xtext 2.9, can you make sure you are on a more recent version?

**Comment by dantonini** [comment]
Hi Stefan,

Yes I use the more recent version I can use with Java 7, or I think so.

In build. gradle I apply gradle xtend plugin 1.0.17 and use xtend-lib 2.10
in dependency.compile .

Is this all I need to configure? Or am I missing something?

Regards

On 14 Apr 2017 17:56, "Stefan Oehme" <notifications@github.com> wrote:

The exception is coming from Xtext or JDT, so this is untelated to the
Gradle plugin. I remember this problem from Xtext 2.9, can you make sure
you are on a more recent version?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/xtext/xtext-gradle-plugin/issues/82#issuecomment-294179401>,
or mute the thread

**Comment by oehme** [comment]
I think this was only fixed in Xtext 2.11
