### ISSUE TITLE
Bug with AssertJ and primitives

### ISSUE THREAD

**Issue by togliu** [xtext/xtext-gradle-plugin#88]
Hello,

if you use Xtend, Gradle and AssertJ and your test looks like 

`@Test
  def void assertBoolean() {
    val b = false
    assertThat(b).isFalse
  }`

the Xtext Gradle plugin will throw an exception and the following message will be printed:

`:generateTestXtext FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':generateTestXtext'.
> Constraints may not be primitives`

Eclipse runs the tests without any errors.

I created a sample project:
https://github.com/togliu/xtend-assertj-bug-sample

By the way there is a strange output too but I think it does not have anything to do with the bug above.

`Warning: NLS unused message: line_separator_platform_mac_os_9 in: org.eclipse.core.internal.runtime.messages
Warning: NLS missing message: auth_alreadySpecified in: org.eclipse.core.internal.runtime.messages
Warning: NLS missing message: plugin_unableToGetActivator in: org.eclipse.core.internal.runtime.messages`

Thanks for your time, help and great work!

Lars

**Comment by cdietrich** [comment]
error is

```
Caused by: java.lang.IllegalArgumentException: Constraints may not be primitives
	at org.eclipse.xtext.xbase.typesystem.references.WildcardTypeReference.setLowerBound(WildcardTypeReference.java:299)
	at org.eclipse.xtext.xbase.typesystem.util.TypeParameterSubstitutor.doVisitWildcardTypeReference(TypeParameterSubstitutor.java:177)
	at org.eclipse.xtext.xbase.typesystem.util.TypeParameterSubstitutor.doVisitWildcardTypeReference(TypeParameterSubstitutor.java:36)
	at org.eclipse.xtext.xbase.typesystem.references.WildcardTypeReference.accept(WildcardTypeReference.java:366)
	at org.eclipse.xtext.xbase.typesystem.util.TypeParameterSubstitutor.visitTypeArgument(TypeParameterSubstitutor.java:103)
	at org.eclipse.xtext.xbase.typesystem.util.TypeParameterSubstitutor.visitTypeArgument(TypeParameterSubstitutor.java:96)
	at org.ec
```

which is 

https://bugs.eclipse.org/bugs/show_bug.cgi?id=485032

(and happens in eclipse as well)

and is fixed in xtext 2.13

**Comment by cdietrich** [comment]
you can test it with

```
repositories {
	maven { url 'https://oss.sonatype.org/content/repositories/snapshots' }
	jcenter()
}

dependencies {
	compile 'org.eclipse.xtend:org.eclipse.xtend.lib:2.13.0-SNAPSHOT'
....
```

**Comment by togliu** [comment]
I tested it and it works. When will the version 2.13.0 be released?
Thanks for the quick response and I think the issue can be closed because it is solved.
And sorry that I bother you.

**Comment by cdietrich** [comment]
there is no release date yet ;) i did this particular fix just this week
