### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: -1

### ISSUE THREAD

**Issue by wagnerma** [xtext/xtext-gradle-plugin#90]
I have an extend project, running fine in Eclipse, generating documentation from our xtext language, but running it with the gradle plugin Buildship, I have a strange exception:
```
Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':compileJava'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:98)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:68)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:236)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:228)
	at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:61)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:228)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:215)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:77)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:58)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:32)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:113)
	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
	at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
	at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
	at org.gradle.initialization.DefaultGradleLauncher$RunTasksAction.execute(DefaultGradleLauncher.java:230)
	at org.gradle.initialization.DefaultGradleLauncher$RunTasksAction.execute(DefaultGradleLauncher.java:227)
	at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:56)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:161)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:112)
	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:95)
	at org.gradle.launcher.exec.GradleBuildController.run(GradleBuildController.java:66)
	at org.gradle.tooling.internal.provider.runner.BuildModelActionRunner.run(BuildModelActionRunner.java:50)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.tooling.internal.provider.runner.RunAsBuildOperationBuildActionRunner$1.execute(RunAsBuildOperationBuildActionRunner.java:43)
	at org.gradle.tooling.internal.provider.runner.RunAsBuildOperationBuildActionRunner$1.execute(RunAsBuildOperationBuildActionRunner.java:40)
	at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:56)
	at org.gradle.tooling.internal.provider.runner.RunAsBuildOperationBuildActionRunner.run(RunAsBuildOperationBuildActionRunner.java:40)
	at org.gradle.tooling.internal.provider.runner.SubscribableBuildActionRunner.run(SubscribableBuildActionRunner.java:88)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:41)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:75)
	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:49)
	at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:49)
	at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:31)
	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:67)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
	at org.gradle.util.Swapper.swap(Swapper.java:38)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)
Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
	at org.eclipse.jdt.internal.compiler.parser.Parser.parse(Parser.java:11140)
	at org.eclipse.jdt.internal.compiler.parser.Parser.parse(Parser.java:11389)
	at org.eclipse.jdt.internal.compiler.parser.Parser.parse(Parser.java:11346)
	at org.eclipse.jdt.internal.compiler.parser.Parser.dietParse(Parser.java:9760)
	at org.eclipse.jdt.internal.compiler.Compiler.internalBeginToCompile(Compiler.java:815)
	at org.eclipse.jdt.internal.compiler.Compiler.beginToCompile(Compiler.java:385)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:431)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:417)
	at org.eclipse.xtext.java.resource.JavaDerivedStateComputer.installFull(JavaDerivedStateComputer.java:227)
	at org.eclipse.xtext.java.resource.JavaResource.lambda$installFull$1(JavaResource.java:192)
	at org.eclipse.xtext.java.resource.JavaResource.initializing(JavaResource.java:201)
	at org.eclipse.xtext.java.resource.JavaResource.installFull(JavaResource.java:195)
	at org.eclipse.xtext.java.resource.JavaResource.getContents(JavaResource.java:165)
	at org.xtext.gradle.builder.DebugInfoInstaller.installDebugInfo(DebugInfoInstaller.java:80)
	at org.xtext.gradle.builder.DebugInfoInstaller.installDebugInfo(DebugInfoInstaller.java:56)
	at org.xtext.gradle.builder.XtextGradleBuilder.installDebugInfo(XtextGradleBuilder.java:659)
	at org.xtext.gradle.tasks.XtextGenerate.installDebugInfo(XtextGenerate.java:410)
	at org.xtext.gradle.XtextBuilderPlugin$6$3$1$1$7.execute(XtextBuilderPlugin.java:443)
	at org.xtext.gradle.XtextBuilderPlugin$6$3$1$1$7.execute(XtextBuilderPlugin.java:440)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:692)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:675)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.execute(ExecuteActionsTaskExecuter.java:115)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.execute(ExecuteActionsTaskExecuter.java:109)
	at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:56)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:109)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:90)
	... 78 more
````

My gradle file looks like:

```
buildscript {
	repositories {
		jcenter()
		mavenCentral()
		maven { url "http://jaspersoft.artifactoryonline.com/jaspersoft/jr-ce-releases" }
		maven { url "http://jaspersoft.artifactoryonline.com/jaspersoft/third-party-ce-artifacts" }
		maven { url "https://repo.eclipse.org/content/groups/releases" }
		ivy {
			url "sftp://88.198.192.147:22/var/ivyrep"
			layout "pattern", {
				artifact "[organisation]/[module]/[revision]/[type]s/[artifact]-[revision].[ext]"
				ivy "[organisation]/[module]/ivy-[revision].xml"
			}
			credentials {
				username '*****'
				password '****'
			}
		}
	}
	dependencies {
		classpath 'org.xtext:xtext-gradle-plugin:1.0.18'
    	classpath "de.effectivecompany.dsl.bl:de.effectivecompany.dsl.bl:2.0.77"
		classpath "de.effective-company:efc_base:2.1.12"
		classpath "org.eclipse.emf:org.eclipse.emf.mwe.utils:1.3.21.201705291010"
		classpath files("${rootProject.projectDir}/bin")
	}
}

apply plugin: "org.xtext.xtend"
apply plugin: "java"
apply plugin: "eclipse"

sourceSets {
	main {
		java {
			srcDirs = ["src"]
		}
		xtendOutputDir = "xtend-gen"
	}
}

repositories {
	mavenCentral()
	maven { url "http://jaspersoft.artifactoryonline.com/jaspersoft/jr-ce-releases" }
	maven { url "http://jaspersoft.artifactoryonline.com/jaspersoft/third-party-ce-artifacts" }
	maven { url "https://repo.eclipse.org/content/groups/releases" }
	ivy {
		url "sftp://88.198.192.147:22/var/ivyrep"
		layout "pattern", {
			artifact "[organisation]/[module]/[revision]/[type]s/[artifact]-[revision].[ext]"
			ivy "[organisation]/[module]/ivy-[revision].xml"
		}
		credentials {
			username '*****'
			password '*****'
		}
	}
}

dependencies {
	compile 'org.eclipse.xtend:org.eclipse.xtend.lib:2.9.0'
	compile "de.effectivecompany.dsl.bl:de.effectivecompany.dsl.bl:2.0.77"
	compile "org.eclipse.xtext:org.eclipse.xtext:2.12.0"
	compile "org.eclipse.xtext:org.eclipse.xtext.xbase:2.12.0"
	compile "org.eclipse.emf:org.eclipse.emf.mwe.utils:1.3.21.201705291010"
}

eclipse {
	project {
	  natures 'org.eclipse.buildship.core.gradleprojectnature'
	  buildCommand 'org.eclipse.buildship.core.gradleprojectbuilder'
	}
}

 task createApiDoc(dependsOn: "eclipse") {
	group = "efc"
	description = "create the EFC API doc"
	doLast {
		new org.eclipse.emf.mwe.utils.StandaloneSetup().setPlatformUri("../")
		com.google.inject.Injector injector = new de.effectivecompany.dsl.bl.EfcBlStandaloneSetup().createInjectorAndDoEMFRegistration()

		// obtain a resourceset from the injector
		org.eclipse.xtext.resource.XtextResourceSet resourceSet = injector.getInstance(org.eclipse.xtext.resource.XtextResourceSet.class)
		resourceSet.addLoadOption(org.eclipse.xtext.resource.XtextResource.OPTION_RESOLVE_ALL, java.lang.Boolean.TRUE);
		// load a resource by URI, in this case from the file system
		org.eclipse.xtext.generator.JavaIoFileSystemAccess fsa = injector.getInstance(org.eclipse.xtext.generator.JavaIoFileSystemAccess.class)
		
		def defaultOutput = new org.eclipse.xtext.generator.OutputConfiguration(org.eclipse.xtext.generator.IFileSystemAccess.DEFAULT_OUTPUT)
		defaultOutput.setDescription("Doc Output Folder")
		defaultOutput.setOutputDirectory("${rootProject.projectDir}/doc-gen")
		defaultOutput.setOverrideExistingResources(true)
		defaultOutput.setCreateOutputDirectory(true)
		defaultOutput.setCleanUpDerivedResources(true)
		defaultOutput.setSetDerivedProperty(true)

		def configurations = [:]
		configurations[defaultOutput.name] = defaultOutput
		fsa.setOutputConfigurations(configurations)
		org.eclipse.xtext.generator.IGenerator2 generator = injector.getInstance(de.effectivecompany.apidoc.Generator.class)
		
		def list = []
		def resMap = [:]
		def dir = new java.io.File("${rootProject.projectDir}/../efc_server/src/efcbl")
		dir.eachFileRecurse(groovy.io.FileType.FILES) { file ->
			list << file
		}
		list.each {
			resMap[it.path] = resourceSet.getResource(org.eclipse.emf.common.util.URI.createFileURI( it.path ), true)
		}
		org.eclipse.xtext.generator.GeneratorContext context = new org.eclipse.xtext.generator.GeneratorContext()
		context.setCancelIndicator(org.eclipse.xtext.util.CancelIndicator.NullImpl);

		// build for each file
		resMap.each { entry ->
			try {
				System.out.println("Generating EFC doc for: " + entry.value.URI)
				generator.doGenerate(entry.value, fsa, context)
			} catch (java.lang.Exception e)
			{
				e.printStackTrace()
			}
		}
		// global build over all files
		try {
			System.out.println("Generating EFC doc for golabl definition:")
			generator.doGenerate(resMap, fsa, context)
		} catch (java.lang.Exception e)
		{
			e.printStackTrace()
		}
	}
}
````

Well the error seems the java compiler want's to compile the extend files? If I use empty extend files, the error is gone.
Any ideas, what is going wrong?
Thanks!
Marcel

**Comment by oehme** [comment]
You are using Xtend 2.9.0, which pulls in an outdated version of the Java parser. Please use 2.12. Feel free to reopen if the problem persists.

**Comment by wagnerma** [comment]
Well, I tried it:

```
dependencies {
	compile 'org.eclipse.xtend:org.eclipse.xtend.lib:2.12.0'
	compile "de.effectivecompany.dsl.bl:de.effectivecompany.dsl.bl:2.0.77"
	compile "org.eclipse.xtext:org.eclipse.xtext:2.12.0"
	compile "org.eclipse.xtext:org.eclipse.xtext.xbase:2.12.0"
	compile "org.eclipse.emf:org.eclipse.emf.mwe.utils:1.3.21.201705291010"
}

```

But same error? Anything else, I can do?

**Comment by oehme** [comment]
Any chance you can reproduce this problem with an example project on GitHub?

A [build scan](https://scans.gradle.com/get-started) might also help diagnose the issue.
