### ISSUE TITLE
Idea plugin does not work when using Maven as preferred build tool

### ISSUE THREAD

**Issue by hristo-vrigazov** [xtext/xtext-gradle-plugin#94]
Eclipse information:
```
Version: Oxygen Release (4.7.0)
Build id: 20170620-1800
```
Xtext information:
```
Xtext Complete SDK	2.12.0.v20170519-1412	org.eclipse.xtext.sdk.feature.group	Eclipse Xtext
```

Use case: As a developer, I want to be able to deploy editors for my language for web, Eclipse and IntelliJ.

Steps to reproduce:

1.  `File -> New -> Project -> Xtext Project`
2.  Leave the defaults and click `Next`:
![image](https://user-images.githubusercontent.com/14914140/29231429-caee0cba-7eef-11e7-866a-b24bee40cd96.png)
3. At the next window, select everything, since I want to be able to deploy editors for all. On the preferred build system, select Maven, because an error is shown that says that for the web integration project, a preferred build system is required.
![image](https://user-images.githubusercontent.com/14914140/29231503-221590d0-7ef0-11e7-851a-3cd45da23334.png)
4. Click `Finish`
5. Generate language artifacts

Expected: No errors occur
Actual: The IDEA project is full of errors "cannot be resolved to a type"
![image](https://user-images.githubusercontent.com/14914140/29231711-e221ed6a-7ef0-11e7-996c-3ec2226ade84.png)

**Comment by cdietrich** [comment]
Xtext Idea Support is more dead than alive see https://github.com/eclipse/xtext-idea/issues and https://www.eclipse.org/Xtext/releasenotes.html#/releasenotes/2017/02/01/version-2-11-0

**Comment by oehme** [comment]
In that case I'd recommend disabling the checkbox in the project wizard. 

@hristo-vrigazov is the idea project correctly recognized as a Gradle project? If not, this might be a problem in what the wizard generated.

**Comment by hristo-vrigazov** [comment]
@oehme @cdietrich It is marked as a Gradle project. I tried downgrading to 2.9.0 (it was the version I used some months ago that worked I think) , since it looked like the last version to support Eclipse, Idea and web plugins with no bugs at startup, but it won't work now (see log below). It looks like http://download.itemis.com/updates/ is now down - it was last up on 9 August based on Google cache. What would you guys recommend as a workaround? I have a very simple language as a replacement for XML configuration and what I really need is the integration with all Eclipse, IntelliJ and web, so I am OK to use an older version provided that it works.

```
0    [main] INFO  text.xtext.generator.XtextGenerator  - Initializing Xtext generator
16   [main] INFO  lipse.emf.mwe.utils.StandaloneSetup  - Adding generated EPackage 'org.eclipse.xtext.common.types.TypesPackage'
214  [main] INFO  lipse.emf.mwe.utils.StandaloneSetup  - Registering project org.xtext.example.mydsl at 'file:/home/hvrigazov/workspace/bromium-dsl/org.xtext.example.mydsl.parent/org.xtext.example.mydsl/'
214  [main] INFO  lipse.emf.mwe.utils.StandaloneSetup  - Registering project org.xtext.example.mydsl.tests at 'file:/home/hvrigazov/workspace/bromium-dsl/org.xtext.example.mydsl.parent/org.xtext.example.mydsl.tests/'
214  [main] INFO  lipse.emf.mwe.utils.StandaloneSetup  - Registering project org.xtext.example.mydsl.ide at 'file:/home/hvrigazov/workspace/bromium-dsl/org.xtext.example.mydsl.parent/org.xtext.example.mydsl.ide/'
215  [main] INFO  lipse.emf.mwe.utils.StandaloneSetup  - Registering project org.xtext.example.mydsl.ui at 'file:/home/hvrigazov/workspace/bromium-dsl/org.xtext.example.mydsl.parent/org.xtext.example.mydsl.ui/'
215  [main] INFO  lipse.emf.mwe.utils.StandaloneSetup  - Registering project org.xtext.example.mydsl.ui.tests at 'file:/home/hvrigazov/workspace/bromium-dsl/org.xtext.example.mydsl.parent/org.xtext.example.mydsl.ui.tests/'
215  [main] INFO  lipse.emf.mwe.utils.StandaloneSetup  - Registering project org.xtext.example.mydsl.idea at 'file:/home/hvrigazov/workspace/bromium-dsl/org.xtext.example.mydsl.parent/org.xtext.example.mydsl.idea/'
215  [main] INFO  lipse.emf.mwe.utils.StandaloneSetup  - Registering project org.xtext.example.mydsl.web at 'file:/home/hvrigazov/workspace/bromium-dsl/org.xtext.example.mydsl.parent/org.xtext.example.mydsl.web/'
230  [main] INFO  lipse.emf.mwe.utils.StandaloneSetup  - Using resourceSet registry. The registered Packages will not be registered in the global EPackage.Registry.INSTANCE!
949  [main] INFO  clipse.emf.mwe.utils.GenModelHelper  - Registered GenModel 'http://www.eclipse.org/Xtext/Xbase/XAnnotations' from 'platform:/resource/org.eclipse.xtext.xbase/model/Xbase.genmodel'
962  [main] INFO  clipse.emf.mwe.utils.GenModelHelper  - Registered GenModel 'http://www.eclipse.org/xtext/xbase/Xtype' from 'platform:/resource/org.eclipse.xtext.xbase/model/Xbase.genmodel'
996  [main] INFO  clipse.emf.mwe.utils.GenModelHelper  - Registered GenModel 'http://www.eclipse.org/xtext/xbase/Xbase' from 'platform:/resource/org.eclipse.xtext.xbase/model/Xbase.genmodel'
997  [main] INFO  clipse.emf.mwe.utils.GenModelHelper  - Registered GenModel 'http://www.eclipse.org/xtext/common/JavaVMTypes' from 'platform:/resource/org.eclipse.xtext.common.types/model/JavaVMTypes.genmodel'
2127 [main] INFO  erator.parser.antlr.AntlrToolFacade  - downloading file from 'http://download.itemis.com/antlr-generator-3.2.0-patch.jar' ...
Downloading ANTLR parser generator failed: No route to host (Host unreachable)
Please install the feature 'Xtext Antlr SDK' manually using the external updatesite:

		'http://download.itemis.com/updates/'.

(see http://www.eclipse.org/Xtext/download.html for details)
5213 [main] INFO  erator.parser.antlr.AntlrToolFacade  - downloading file from 'http://download.itemis.com/antlr-generator-3.2.0-patch.jar' ...
Downloading ANTLR parser generator failed: No route to host (Host unreachable)
Please install the feature 'Xtext Antlr SDK' manually using the external updatesite:

		'http://download.itemis.com/updates/'.

(see http://www.eclipse.org/Xtext/download.html for details)
8241 [main] ERROR mf.mwe2.launch.runtime.Mwe2Launcher  - Problems running workflow org.xtext.example.mydsl.GenerateMyDsl: 
[ERROR]: 

*ATTENTION*
It is highly recommended to use ANTLR's parser generator (get it from 'http://xtext.itemis.com/'). 
As an alternative to ANTLR you could also use the alternative implementation shipped with Xtext.
To do so use the generator fragment 'org.eclipse.xtext.generator.parser.packrat.PackratParserFragment' in your mwe2 file instead.(Element: -UNKNOWN-; Reported by: XtextGenerator)
[ERROR]: 

*ATTENTION*
It is highly recommended to use ANTLR's parser generator (get it from 'http://xtext.itemis.com/'). 
As an alternative to ANTLR you could also use the alternative implementation shipped with Xtext.
To do so use the generator fragment 'org.eclipse.xtext.generator.parser.packrat.PackratParserFragment' in your mwe2 file instead.(Element: -UNKNOWN-; Reported by: XtextGenerator)
java.lang.RuntimeException: Problems running workflow org.xtext.example.mydsl.GenerateMyDsl: 
[ERROR]: 

*ATTENTION*
It is highly recommended to use ANTLR's parser generator (get it from 'http://xtext.itemis.com/'). 
As an alternative to ANTLR you could also use the alternative implementation shipped with Xtext.
To do so use the generator fragment 'org.eclipse.xtext.generator.parser.packrat.PackratParserFragment' in your mwe2 file instead.(Element: -UNKNOWN-; Reported by: XtextGenerator)
[ERROR]: 

*ATTENTION*
It is highly recommended to use ANTLR's parser generator (get it from 'http://xtext.itemis.com/'). 
As an alternative to ANTLR you could also use the alternative implementation shipped with Xtext.
To do so use the generator fragment 'org.eclipse.xtext.generator.parser.packrat.PackratParserFragment' in your mwe2 file instead.(Element: -UNKNOWN-; Reported by: XtextGenerator)
	at org.eclipse.emf.mwe2.launch.runtime.Mwe2Runner.run(Mwe2Runner.java:104)
	at org.eclipse.emf.mwe2.launch.runtime.Mwe2Runner.run(Mwe2Runner.java:62)
	at org.eclipse.emf.mwe2.launch.runtime.Mwe2Runner.run(Mwe2Runner.java:52)
	at org.eclipse.emf.mwe2.launch.runtime.Mwe2Launcher.run(Mwe2Launcher.java:78)
	at org.eclipse.emf.mwe2.launch.runtime.Mwe2Launcher.main(Mwe2Launcher.java:36)
Caused by: java.lang.RuntimeException: 
[ERROR]: 

*ATTENTION*
It is highly recommended to use ANTLR's parser generator (get it from 'http://xtext.itemis.com/'). 
As an alternative to ANTLR you could also use the alternative implementation shipped with Xtext.
To do so use the generator fragment 'org.eclipse.xtext.generator.parser.packrat.PackratParserFragment' in your mwe2 file instead.(Element: -UNKNOWN-; Reported by: XtextGenerator)
[ERROR]: 

*ATTENTION*
It is highly recommended to use ANTLR's parser generator (get it from 'http://xtext.itemis.com/'). 
As an alternative to ANTLR you could also use the alternative implementation shipped with Xtext.
To do so use the generator fragment 'org.eclipse.xtext.generator.parser.packrat.PackratParserFragment' in your mwe2 file instead.(Element: -UNKNOWN-; Reported by: XtextGenerator)
	at org.eclipse.emf.mwe.core.lib.Mwe2Bridge.handleIssues(Mwe2Bridge.java:56)
	at org.eclipse.emf.mwe.core.lib.Mwe2Bridge.preInvoke(Mwe2Bridge.java:66)
	at org.eclipse.emf.mwe.core.lib.AbstractWorkflowComponent.preInvoke(AbstractWorkflowComponent.java:197)
	at org.eclipse.emf.mwe2.runtime.workflow.AbstractCompositeWorkflowComponent.preInvoke(AbstractCompositeWorkflowComponent.java:29)
	at org.eclipse.emf.mwe2.runtime.workflow.Workflow.run(Workflow.java:18)
	at org.eclipse.emf.mwe2.la
```

**Comment by cdietrich** [comment]
opened a ticket regarding http://download.itemis.com/updates/ down

**Comment by cdietrich** [comment]
you can take the jar from here 
https://github.com/cdietrich/mql/blob/master/org.eclipse.xtext.mql/.antlr-generator-3.2.0-patch.jar

**Comment by hristo-vrigazov** [comment]
Ok, so where should I put it and do I have to make changes to the mwe2 file?

**Comment by cdietrich** [comment]
simply put it in the root of the xxx.mydsl project

**Comment by hristo-vrigazov** [comment]
It still tries to download it and the "Generate language artifact" part fails.

**Comment by cdietrich** [comment]
sure you named it right `.antlr-generator-3.2.0-patch.jar` and put in the root of the project that contains the mwe?

**Comment by hristo-vrigazov** [comment]
Yes, when downloading Chrome removed the dot, now it is able to build the language artifacts, but web and idea won't work, so I guess I will leave IntelliJ for now.

**Comment by cdietrich** [comment]
web actually should

**Comment by cdietrich** [comment]
(maybe if you select both idea and web something gets disturbed)

**Comment by hristo-vrigazov** [comment]
Here is the stack trace:
```
[main] INFO org.eclipse.jetty.util.log - Logging initialized @521ms
[main] INFO org.eclipse.jetty.server.Server - jetty-9.2.11.v20150529
[main] INFO org.eclipse.jetty.webapp.StandardDescriptorProcessor - NO JSP Support for /, did not find org.eclipse.jetty.jsp.JettyJspServlet
[main] INFO org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.w.WebAppContext@3701eaf6{/,[file:/home/hvrigazov/workspace/bromium-dsl/org.xtext.example.mydsl.parent/org.xtext.example.mydsl.web/WebRoot/, jar:file:/home/hvrigazov/.m2/repository/org/eclipse/xtext/org.eclipse.xtext.web/2.9.2/org.eclipse.xtext.web-2.9.2.jar!/META-INF/resources, jar:file:/home/hvrigazov/.m2/repository/org/webjars/requirejs/2.1.20/requirejs-2.1.20.jar!/META-INF/resources, jar:file:/home/hvrigazov/.m2/repository/org/webjars/ace/1.2.0/ace-1.2.0.jar!/META-INF/resources, jar:file:/home/hvrigazov/.m2/repository/org/webjars/jquery/2.1.4/jquery-2.1.4.jar!/META-INF/resources],AVAILABLE}
[main] INFO org.eclipse.jetty.server.ServerConnector - Started ServerConnector@a7e666{HTTP/1.1}{localhost:8080}
[main] INFO org.eclipse.jetty.server.Server - Started @11356ms
[main] INFO org.xtext.example.mydsl.web.ServerLauncher - Server started http://localhost:8080/...
[Thread-9] INFO org.xtext.example.mydsl.web.ServerLauncher - Press enter to stop the server...
[qtp1768305536-10] WARN org.eclipse.jetty.server.ResourceCache - 
java.util.zip.ZipException: invalid LOC header (bad signature)
	at java.util.zip.ZipFile.read(Native Method)
	at java.util.zip.ZipFile.access$1400(ZipFile.java:60)
	at java.util.zip.ZipFile$ZipFileInputStream.read(ZipFile.java:717)
	at java.util.zip.ZipFile$ZipFileInflaterInputStream.fill(ZipFile.java:419)
	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at org.eclipse.jetty.util.BufferUtil.readFrom(BufferUtil.java:454)
	at org.eclipse.jetty.util.BufferUtil.toBuffer(BufferUtil.java:889)
	at org.eclipse.jetty.server.ResourceCache.getDirectBuffer(ResourceCache.java:303)
	at org.eclipse.jetty.server.ResourceCache$Content.getDirectBuffer(ResourceCache.java:463)
	at org.eclipse.jetty.server.HttpOutput.sendContent(HttpOutput.java:665)
	at org.eclipse.jetty.server.HttpOutput.sendContent(HttpOutput.java:576)
	at org.eclipse.jetty.servlet.DefaultServlet.sendData(DefaultServlet.java:955)
	at org.eclipse.jetty.servlet.DefaultServlet.doGet(DefaultServlet.java:533)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:748)
[qtp1768305536-10] WARN org.eclipse.jetty.server.ResourceCache - Could not load CachedContent@2742e148{r=jar:file:/home/hvrigazov/.m2/repository/org/webjars/jquery/2.1.4/jquery-2.1.4.jar!/META-INF/resources/webjars/jquery/2.1.4/jquery.min.js,e=true,lm=Wed, 29 Apr 2015 20:40:32 GMT,ct=java.nio.HeapByteBuffer[pos=0 lim=22 cap=22]}
[qtp1768305536-10] WARN org.eclipse.jetty.server.ResourceCache - 
java.util.zip.ZipException: invalid LOC header (bad signature)
	at java.util.zip.ZipFile.read(Native Method)
	at java.util.zip.ZipFile.access$1400(ZipFile.java:60)
	at java.util.zip.ZipFile$ZipFileInputStream.read(ZipFile.java:717)
	at java.util.zip.ZipFile$ZipFileInflaterInputStream.fill(ZipFile.java:419)
	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at org.eclipse.jetty.util.BufferUtil.readFrom(BufferUtil.java:454)
	at org.eclipse.jetty.util.BufferUtil.toBuffer(BufferUtil.java:889)
	at org.eclipse.jetty.server.ResourceCache.getIndirectBuffer(ResourceCache.java:286)
	at org.eclipse.jetty.server.ResourceCache$Content.getIndirectBuffer(ResourceCache.java:441)
	at org.eclipse.jetty.server.HttpOutput.sendContent(HttpOutput.java:667)
	at org.eclipse.jetty.server.HttpOutput.sendContent(HttpOutput.java:576)
	at org.eclipse.jetty.servlet.DefaultServlet.sendData(DefaultServlet.java:955)
	at org.eclipse.jetty.servlet.DefaultServlet.doGet(DefaultServlet.java:533)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:748)
[qtp1768305536-10] WARN org.eclipse.jetty.server.ResourceCache - Could not load CachedContent@2742e148{r=jar:file:/home/hvrigazov/.m2/repository/org/webjars/jquery/2.1.4/jquery-2.1.4.jar!/META-INF/resources/webjars/jquery/2.1.4/jquery.min.js,e=true,lm=Wed, 29 Apr 2015 20:40:32 GMT,ct=java.nio.HeapByteBuffer[pos=0 lim=22 cap=22]}
[qtp1768305536-10] WARN org.eclipse.jetty.server.ResourceCache - 
java.util.zip.ZipException: invalid LOC header (bad signature)
	at java.util.zip.ZipFile.read(Native Method)
	at java.util.zip.ZipFile.access$1400(ZipFile.java:60)
	at java.util.zip.ZipFile$ZipFileInputStream.read(ZipFile.java:717)
	at java.util.zip.ZipFile$ZipFileInflaterInputStream.fill(ZipFile.java:419)
	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at org.eclipse.jetty.util.BufferUtil.readFrom(BufferUtil.java:454)
	at org.eclipse.jetty.util.BufferUtil.toBuffer(BufferUtil.java:889)
	at org.eclipse.jetty.server.ResourceCache.getIndirectBuffer(ResourceCache.java:286)
	at org.eclipse.jetty.server.ResourceCache$Content.getIndirectBuffer(ResourceCache.java:441)
	at org.eclipse.jetty.server.ResourceCache$Content.getInputStream(ResourceCache.java:488)
	at org.eclipse.jetty.server.HttpOutput.sendContent(HttpOutput.java:690)
	at org.eclipse.jetty.server.HttpOutput.sendContent(HttpOutput.java:576)
	at org.eclipse.jetty.servlet.DefaultServlet.sendData(DefaultServlet.java:955)
	at org.eclipse.jetty.servlet.DefaultServlet.doGet(DefaultServlet.java:533)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:748)
[qtp1768305536-10] WARN org.eclipse.jetty.server.ResourceCache - Could not load CachedContent@2742e148{r=jar:file:/home/hvrigazov/.m2/repository/org/webjars/jquery/2.1.4/jquery-2.1.4.jar!/META-INF/resources/webjars/jquery/2.1.4/jquery.min.js,e=true,lm=Wed, 29 Apr 2015 20:40:32 GMT,ct=java.nio.HeapByteBuffer[pos=0 lim=22 cap=22]}
[qtp1768305536-10] WARN org.eclipse.jetty.servlet.ServletHandler - /webjars/jquery/2.1.4/jquery.min.js
java.util.zip.ZipException: invalid LOC header (bad signature)
	at java.util.zip.ZipFile.read(Native Method)
	at java.util.zip.ZipFile.access$1400(ZipFile.java:60)
	at java.util.zip.ZipFile$ZipFileInputStream.read(ZipFile.java:717)
	at java.util.zip.ZipFile$ZipFileInflaterInputStream.fill(ZipFile.java:419)
	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at org.eclipse.jetty.server.HttpOutput$InputStreamWritingCB.process(HttpOutput.java:1041)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:246)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:208)
	at org.eclipse.jetty.server.HttpOutput.sendContent(HttpOutput.java:613)
	at org.eclipse.jetty.server.HttpOutput.sendContent(HttpOutput.java:695)
	at org.eclipse.jetty.server.HttpOutput.sendContent(HttpOutput.java:576)
	at org.eclipse.jetty.servlet.DefaultServlet.sendData(DefaultServlet.java:955)
	at org.eclipse.jetty.servlet.DefaultServlet.doGet(DefaultServlet.java:533)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by cdietrich** [comment]
do you use maven or gradle.
do you have m2 or buildship installed?
for me it looks like the download of the webjars failed.
have no idea what could have caused that

**Comment by hristo-vrigazov** [comment]
I selected Maven as preferred build tool, but since I wanted IntelliJ build as well, it automatically created Gradle build also

**Comment by cdietrich** [comment]
maybr you should try a pure maven or a pure gradle project

**Comment by hristo-vrigazov** [comment]
It is impossible I think. Selecting checkboxes in the wizard kind of feels like solving a constraint satisfaction problem :laughing:

**Comment by cdietrich** [comment]
simply dont select idea, and select gradle or maven. i am in favour of throwing idea away anyway. dont know why we still keep this option. maybe there is still the hope that somebody steps up to fix it

**Comment by hristo-vrigazov** [comment]
Yes, so as I mentioned, I really need IDEA and since I remembered that it was possible to build for all the tree at the same time, I tried an older version of Xtext - 2.9.0, which I thought was still supporting it. If I don't select IDEA others would work. I would love to help with maintaining IDEA plugin but I don't feel like I know enough about IDEs in general, so let's hope a hero shows up

**Comment by cdietrich** [comment]
well then you need to stick with the old xtext 2.9 or 2.10
